MP3/views/admin.py
import csv
import io
from flask import Blueprint, render_template, request, redirect, flash
from werkzeug.utils import secure_filename
from sql.db import DB
import traceback
admin = Blueprint('admin', __name__, url_prefix='/admin')

@admin.route("/import", methods=["GET","POST"])
def importCSV():
    if request.method == "POST":
        if 'file' not in request.files:
            return redirect(request.url)
        file = request.files['file']
        # If the user does not select a file, the browser submits an
        # empty file without a filename.
        if file.filename == '':
            flash('No selected file', "warning")
            return redirect(request.url)
        # TODO importcsv-1 check that it's a .csv file, return a proper flash message if it's not and don't attempt to process the file
        # RK868 11/23/23
        if file and secure_filename(file.filename):
            if not file.filename.endswith('.csv'):
                flash('Invalid file format. Please upload a .csv file.', 'error')
                return redirect(request.url)
            organizations = []
            donations = []
            # DON'T EDIT
            organization_query = """
            INSERT INTO IS601_MP3_Organizations (name, address, city, country, state, zip, website, description)
                        VALUES (%(name)s, %(address)s, %(city)s, %(country)s, %(state)s, %(zip)s, %(website)s, %(description)s)
                        ON DUPLICATE KEY UPDATE 
                        address=values(address),
                        city=values(city),
                        country=values(country),
                        state=values(state),
                        zip=values(zip),
                        website=values(website),
                        description=values(description)
            """
            # DON'T EDIT
            donation_query = """
            INSERT INTO IS601_MP3_Donations (donor_firstname, donor_lastname, donor_email, item_name, item_description, item_quantity, organization_id, donation_date, comments)
                    VALUES (%(donor_firstname)s, %(donor_lastname)s, %(donor_email)s, %(item_name)s, %(item_description)s, %(quantity)s, 
                            (SELECT id FROM IS601_MP3_Organizations WHERE name = %(organization_name)s LIMIT 1), 
                            %(donation_date)s, %(comments)s)
                    ON DUPLICATE KEY UPDATE 
                                            donor_firstname=%(donor_firstname)s,
                                            donor_lastname=%(donor_lastname)s,
                                            donor_email=%(donor_email)s,
                                            item_name=%(item_name)s, 
                                            item_quantity = %(quantity)s,
                                            item_description= %(item_description)s,
                                            comments=%(comments)s, 
                                            organization_id = (SELECT id FROM IS601_MP3_Organizations WHERE name=%(organization_name)s LIMIT 1),
                                            donation_date = %(donation_date)s,
                                            comments=%(comments)s
            """
            # Note: this reads the file as a stream instead of requiring us to save it, don't modify/remove it
            stream = io.TextIOWrapper(file.stream._file, "UTF8", newline=None)
            # TODO importcsv-2 read the csv file stream as a dict
            # RK868 11/23/23
            csv_data = csv.DictReader(stream)
            for row in csv_data:
                # TODO importcsv-3: extract organization data and append to organization list
                # as a dict only with organization data if all organization fields are present (refer to above SQL)
                # RK868 11/23/23
                if row.get('organization_name') and row.get('organization_address') and row.get('organization_city') and row.get('organization_country') and row.get('organization_state') and row.get('organization_zip') and row.get('organization_website') and row.get('organization_description'):
                    organization = {
                        'name': row['organization_name'],
                        'address': row['organization_address'],
                        'city': row['organization_city'],
                        'country': row['organization_country'],
                        'state': row['organization_state'],
                        'zip': row['organization_zip'],
                        'website': row['organization_website'],
                        'description': row['organization_description']
                    }
                    organizations.append(organization)


                # TODO importcsv-4: extract donation data and append to donation list
                # as a dict only with donation data if all donation fields are present (refer to above SQL)
                # RK868 11/23/23
                # rk868 11/26/23 - ad3ded split() to donor_name to separate first and last name
                if row.get('donor_name') and row.get('donor_email') and row.get('item_name') and row.get('item_description') and row.get('item_quantity') and row.get('organization_name') and row.get('donation_date') and row.get('comments'):
                    if row.get('donor_name') and len(row.get('donor_name').split()) > 1:
                        first_name = row.get('donor_name').split()[0]
                        last_name = row.get('donor_name').split()[1]
                    else:
                        first_name = row.get('donor_name')
                        last_name = ''
                    donation = {
                        'donor_firstname': first_name,
                        'donor_lastname': last_name,
                        'donor_email': row.get('donor_email'),
                        'item_name': row.get('item_name'),
                        'item_description': row.get('item_description'),
                        'quantity': row.get('item_quantity'),
                        'organization_name': row.get('organization_name'),
                        'donation_date': row.get('donation_date'),
                        'comments': row.get('comments')
                    }
                    donations.append(donation)

            if len(organizations) > 0:
                print(f"Inserting or updating {len(organizations)} organizations")
                try:
                    result = DB.insertMany(organization_query, organizations)
                    # TODO importcsv-5 display flash message about number of organizations inserted
                    # RK868 11/23/23
                    flash(f"{len(organizations)} organizations inserted", "success")
                except Exception as e:
                    traceback.print_exc()
                    flash("There was an error loading in the csv data", "danger")
            else:
                # TODO importcsv-6 display flash message (info) that no organizations were loaded
                # RK868 11/23/23
                flash("No organizations were loaded", "info")

            if len(donations) > 0:
                print(f"Inserting or updating {len(donations)} donations")
                try:
                    result = DB.insertMany(donation_query, donations)
                    # TODO importcsv-7 display flash message about number of donations loaded
                    # RK868 11/23/23
                    flash(f"{len(donations)} donations loaded", "success")
                except Exception as e:
                    traceback.print_exc()
                    flash("There was an error loading in the csv data", "danger")
            else:
                # TODO importcsv-8 display flash message (info) that no donations were loaded
                # RK868 11/23/23
                flash("No donations were loaded", "info")

            try:
                result = DB.selectOne("SHOW SESSION STATUS LIKE 'questions'")
                print(f"Result {result}")
            except Exception as e:
                traceback.print_exc()
                flash("There was an error counting session queries", "danger")
    return render_template("upload.html")

MP3/views/geography.py
import pycountry
import json
from flask import Blueprint, request

geo = Blueprint("geo", __name__, url_prefix='/geo')
# TODO DO NOT EDIT
# these are javascript endpoints used from country_state_selector.html
@geo.route("/countries")
def countries():
    # extract just the data we need for our <select> options
    countries = map(lambda c: {"code": c.alpha_2, "name": c.name},list(pycountry.countries))
    return json.dumps(list(countries))

@geo.route("/states")
def states():
    # extract just the data we need for our <select> options
    country_code = request.args.get("country_code", default="", type=str)
    states = []
    if country_code.strip():
        states = pycountry.subdivisions.get(country_code=country_code.strip())
    print(f"Found [{len(states)}] states for country_code [{country_code}]")
    if not states:
        states = []
    states = list(map(lambda s: {"name": s.name, "code": s.code.split("-")[1]}, 
        states))
    return json.dumps(states)

MP3/views/index.py
from flask import Blueprint, render_template
home = Blueprint('home', __name__, url_prefix='/')

# TODO DO NOT EDIT
@home.route('/')
def index():
    return render_template("index.html")

MP3/templates/country_state_selector.html
{# TODO DO NOT EDIT #}
{% macro country_state_selector(country="", state="", layout="vertical") %}
{% set c = request.args.get("country", request.form.get("country", country or '')) %}
{% set s = request.args.get("state", request.form.get("state", state or '')) %}
{% if layout and layout == 'horizontal' %}
{# version for filter forms #}
<div class="col">
    <label class="visually-hidden" for="country">Country</label>
    <select name="country" id="country" class="form-select" value="{{c}}"
        onchange="fetchStates(this.value)">
        <option value="">Select Country...</option>
    </select>
</div>
<div class="col">
    <label class="visually-hidden" for="state">State</label>
    <select name="state" id="state" class="form-select" value="{{s}}">
        <option value="">Select State...</option>
    </select>
</div>
{% else %}
{# version for add/edit forms #}
<div class="form-group mb-3">
    <label class="form-label" for="country">Country</label>
    <select name="country" id="country" class="form-select" value="{{c}}"
        required onchange="fetchStates(this.value)">
        <option value="">Select Country...</option>
    </select>
</div>
<div class="form-group mb-3">
    <label class="form-label" for="state">State</label>
    <select name="state" id="state" class="form-select" value="{{s}}" required>
        <option value="">Select State...</option>
    </select>
</div>
{% endif %}
<script>
    //gets called on page load and when the country selection changes
    const fetchStates = (country) => {
        //use jinja to return a string in the html template
        //this string will be as if we did let state = "whatever"
        let state = "{{s}}";
        console.log("fetching", country);
        fetch(`{{url_for('geo.states')}}?country_code=${country}`)
            .then(resp => resp.json())
            .then(data => {
                let ele = document.querySelector("select[name='state']");

                //if we had options, "clear" it to be the default option
                //so appending works
                if (ele.children.length > 1) {
                    ele.innerHTML = `<option value="">Select State...</option>`;
                }
                //dynamically create option tags
                for (let d of data) {
                    let nele = document.createElement("option");
                    nele.value = d.code;
                    nele.innerText = d.name;
                    ele.appendChild(nele);
                }
                //assign the default or args state
                ele.value = state;
            });
    };
    window.addEventListener("load", () => {
        //use jinja to return a string in the html template
        //this string will be as if we did let country = "whatever"
        let country = "{{c}}";
        //get the country list from the endpoint
        fetch(`{{url_for('geo.countries')}}`)
            .then(resp => resp.json())
            .then(data => {
                let ele = document.querySelector("select[name='country']");
                ele.value = "";//clear the value so "onchange" works
                //dynamically create option tags
                for (let d of data) {
                    let nele = document.createElement("option");
                    nele.value = d.code;
                    nele.innerText = d.name;
                    ele.appendChild(nele);
                }
                //assign the default or args country
                ele.value = country;
            })
            .finally(() => {
                //get the state list from the endpoint
                fetchStates(country);
            });
    });
</script>
{% endmacro %}

MP3/templates/flash.html
{# TODO DO NOT EDIT #}
{% with messages = get_flashed_messages(with_categories=true) %}
{% if messages %}
<div class=flashes>
    {% for category, message in messages %}
    <div class="alert alert-{{ category or 'info' }}" role="alert">{{ message }}
    </div>
    {% endfor %}
</div>
{% endif %}
{% endwith %}

MP3/templates/index.html
{% extends "layout.html" %}
{% block title %}Home{% endblock %}
{% block content %}
<div class="container-fluid">
    <div class="h1 text-center text-warning">Thankful Donations</div>
    <div class="w-50 mx-auto bg-light text-center caption border">
        Thankful Donations: Helping organizations share with those in need.
    </div>
    <div class="lead text-center btyb">Brought to you by Rohan Khanna (rk868) from
        section
        IS601-007
    </div>
</div>
{% endblock %}

MP3/templates/layout.html
<!doctype html>
<html>

<head>
    {% block head %}
    <link
        href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.2/dist/css/bootstrap.min.css"
        rel="stylesheet"
        integrity="sha384-Zenh87qX5JnK2Jl0vWa8Ck2rdkQ2Bzep5IDxbcnCeuOxjzrPF/et3URy9Bv1WTRi"
        crossorigin="anonymous">
    <script
        src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.2/dist/js/bootstrap.bundle.min.js"
        integrity="sha384-OERcA2EqjJCMA+/3y+gxIOqMEjwtxJY7qPCqsdltbNJuaOe923+mo//f6V8Qbsw3"
        crossorigin="anonymous"></script>
    <style>
        .footer {
            display: block;
        }

        .header {
            top: 0;
            height: 60px;
            line-height: 60px;
        }

        /* Add style here that'll capitalize all form labels */
    </style>
    <title>{% block title %}{% endblock %} - MP3</title>
    {% endblock %}
</head>

<body>
    <div id="header">
        {% include "nav.html" %}
        {% include 'flash.html' %}
    </div>
    <div id="content" class="overflow-auto" style="height: 84vh">
        {% block content %} {% endblock %}
    </div>
    <div id=" footer"
        class="footer mt-auto py-3 bg-light text-center fixed-bottom">
        <div class="container">
            {% block footer %}
            <span>Thankful Donations &copy; Copyright 2023.</span>
            {% endblock %}
        </div>
    </div>
</body>

</html>

MP3/templates/list_donations.html
{% extends "layout.html" %}
{% block title %}Donations{% endblock %}
{% block content %}
{% from "organization_dropdown.html" import organization_dropdown %}
{% from "sort_filter.html" import sort_filter %}
<div class="container-fluid">
    <div class="h1 text-center">{{organization_name}}
        Donations</div>
    <form method="GET">
        <div class="row">
            {# TODO
            build a horizontal filter/sort form with
            donor first name (show as first name, but name should be fn)
            donor last_name (show as last name, but name should be ln)
            donor email (validate as text, not email, so partial match works)
            item name
            organization (provided) (name is organization value is the id)
            sort/order (using allowed_columns and provided partial template)
            limit (default 10)
            ensure all fields prefill with request arg data if provided
            #} 
            
            <!-- RK868 11/23/23 -->
            <!--first name-->
            <div class="col">
                <input id="fn" class="form-control" placeholder="First Name" name="fn" type="text"
                    value="{{request.args.get('fn') or ''}}">
            </div>
            <!-- RK868 11/23/23 -->
            <!--last name-->
            <div class="col">
                <input id="ln" class="form-control" placeholder="Last Name" name="ln" type="text"
                    value="{{request.args.get('ln') or ''}}">
            </div>
            <!-- RK868 11/23/23 -->
            <!--email-->
            <div class="col">
                <input id="email" class="form-control" placeholder="Email" name="email" type="text"
                    value="{{request.args.get('email') or ''}}">
            </div>
            <!-- RK868 11/23/23 -->
            <!-- item name-->
            <div class="col">
                <input id="item_name" class="form-control" placeholder="Item Name" name="item_name" type="text"
                    value="{{request.args.get('item_name') or ''}}">
            </div>
            <!--organization-->
            <div class="col">
                <label class="visually-hidden"
                    for="organization">Organization</label>
                {{organization_dropdown(request.args.get("organization"))}}
            </div>
            <!-- RK868 11/23/23 -->
            <!-- sort filter -->
            <div class="col">
                <input id="limit" class="form-control" placeholder="limit" name="limit" type="int" value="{{request.args.get('limit') or 10}}">
            </div>
            <!-- RK868 11/23/23 -->
            <!--limit filter-->
            {# TODO pass/set the columns that can be used for sort/filter (i.e. allowed_columns) #}
            <div class="col">
                {{sort_filter(allowed_columns)}}
            </div>
            <div class="col">
                <input type="submit" class="btn btn-primary" value="Filter" />
            </div>
            <div class="col">
                <a href="?" class="btn btn-secondary">Reset</a>
            </div>
        </div>
    </form>
    <table class="table">
        <thead>
            <tr class="text-capitalize">
                {# generate th tags for each column to display #}
                {# don't show any id or organization_id columns #}
                {# IMPORTANT use table column names as the headings, replace _ with space via filter #}
                <!-- add th elements -->
                <th>Donor Firstname</th>
                <th>Donor Lastname</th>
                <th>Donor Email</th>
                <th>Item Name</th>
                <th>Item Description</th>
                <th>Item Quantity</th>
                <th>Donation Date</th>
                <th>Comments</th>
                <th>Organization Name</th>
                <!-- keep this -->
                <!-- RK868 11/23/23 -->
                <th>Actions</th>
            </tr>
        </thead>
        <tbody>
            {% if rows and rows|length > 0 %}
            {% for row in rows %}
            {# generate tr with td tags for each piece of data #}
            {# don't show any id or organization_id columns #}
            {# in the last column add the following
            an edit button that passes the donation id to donation edit
            a delete button that passes the donation id and the request args to the donation delete route
            #}
            <!-- iterate over rows and generate proper tr and td elements with the data -->
            <tr>
                <td>{{ row.donor_firstname }}</td>
                <td>{{ row.donor_lastname}}</td>
                <td>{{ row.donor_email }}</td>
                <td>{{ row.item_name }}</td>
                <td>{{ row.item_description }}</td>
                <td>{{ row.item_quantity }}</td>
                <td>{{ row.donation_date }}</td>
                <td>{{ row.comments }}</td>
                <td>{{ row.name }}</td>
                <td>
                    <a href="{{ url_for('donations.edit', id=row['id']) }}">Edit</a>
                    <a href="{{ url_for('donations.delete', id=row['id'])}}">Delete</a>
                </td>
                <!-- RK868 11/23/23 -->
            </tr>
            {% endfor %}
            {% else %}
            <tr>
                <td colspan="100%">No results to show</td>
            </tr>
            {% endif %}
        </tbody>
    </table>
</div>
{% endblock %}

MP3/templates/list_organizations.html
{% extends "layout.html" %}
{% block title %}Organization Directory{% endblock %}
{% block content %}
{% from "country_state_selector.html" import country_state_selector %}
{% from "sort_filter.html" import sort_filter %}
<div class="container-fluid">
    <div class="h1 text-center">Organization Directory</div>
    <form method="GET">
        <div class="row">
            {# TODO
            build a horizontal filter/sort form with
            name (show as organization name but name field should be name)
            country/state (provided)
            sort/order (using allowed_columns and provided partial template)
            limit (default 10)
            ensure all fields prefill with request arg data if provided
            #}
            <!--name filter-->
            <!-- RK868 11/27/23 -->
            <div class="row">
                <div class="col">
                    <input id="name" class="form-control" placeholder="Name" name="name" type="text"
                        value="{{request.args.get('name') or ''}}">
                </div>
            <!-- country state filter-->
            <!-- RK868 11/27/23 -->  
            {{country_state_selector(layout="horizontal")}}
            <!-- sort filter -->
            <!-- RK868 11/27/23 -->
            {{sort_filter(cols=allowed_columns)}}
            <!--limit filter-->
            <!-- RK868 11/27/23 -->
            <div class="col">
                <input id="limit" type="number" class="form-control" value="10" name="limit" />
            </div>
            {# TODO pass/set the columns that can be used for sort/filter (i.e. allowed_columns) #}

            <div class="col">
                <input type="submit" class="btn btn-primary" value="Filter" />
            </div>
            <div class="col">
                <a href="?" class="btn btn-secondary">Reset</a>
            </div>
        </div>
    </form>
    <div class="table-responsive">
        <table class="table">
            <thead>
                <tr class="text-capitalize">
                    {# generate th tags for each column to display #}
                    {# don't show any id or organization_id columns #}
                    {# IMPORTANT use table column names as the headings, replace _ with space via filter #}
                    <!-- add th elements -->

                    <th>Name</th>
                    <th>Address</th>
                    <th>City</th>
                    <th>State</th>
                    <th>Country</th>
                    <th>Zip</th>
                    <th>Website</th>
                    <th>Donations</th>
                    <!-- keep this -->
                    <th>Actions</th>
                </tr>
            </thead>
            <tbody>
                {# generate tr with td tags for each piece of data #}
                {# don't show any id or organization_id columns #}
                {# if the td is for website, display it as a link where the text is "website" and the url is the
                website url #}
                {# in the last column add the following
                a view button that passes the organization id to donation search (this will be an organization's donation
                list)
                an edit button that passes the organization id to organization edit
                a delete button that passes the organization id and the request args to the organization delete route
                #}
                {% if rows and rows|length > 0 %}
                {% for row in rows %}
                
                <tr>
                    <td>{{ row.name }}</td>
                    <td>{{ row.address }}</td>
                    <td>{{ row.city }}</td>
                    <td>{{ row.state }}</td>
                    <td>{{ row.country }}</td>
                    <td>{{ row.zip }}</td>
                    <td>{% if row.website %}<a href="{{ row.website }}" target="_blank">{{row.website}}</a>{% endif %}</td>
                    <td>{{ row.donations}}</td>
                    <td>
                        <a href="{{ url_for('donations.search', organization_id=row['id']) }}">View</a>
                        <a href="{{ url_for('organization.edit', id=row['id']) }}">Edit</a>
                        <a href="{{ url_for('organization.delete', id=row['id'], **request.args.to_dict()) }}">Delete</a>
                    </td>
                    <!-- RK868 11/27/23 -->
                </tr>
                {% endfor %}
                <!-- iterate over rows and generate proper tr and td elements with the data -->

            </tbody>
            {% else %}
            <tbody>
                <tr>
                    <td colspan="100%">No results to show</td>
                </tr>
            </tbody>
            {% endif %}
        </table>
    </div>
</div>
{% endblock %}

MP3/templates/manage_organization.html
{% extends "layout.html" %}
{% block title %}{{ "Edit" if org.get("id") else "Create" }} Organization{% endblock %}
{% block content %}
{% from "country_state_selector.html" import country_state_selector %}

<div class="container-fluid">
    <div class="h1">{{ "Edit" if org.get("id") else "Create" }} Organization</div>
    <div>
        <form method="POST">
            {#
            using regular HTML generate fields (labels and input; not WTForms) with proper types for
            name (required)
            description (optional)
            address (required)
            city (required) (can be a text field, doesn't need to be a valid city)
            state/country (required) (given)
            zip (required)
            website (optional)
            
            if a validation error occurs, the inserted form data should persist
            #}
            <!-- Organization Name -->
            <!-- RK868 11/24/23 -->
            <div class="mb-3">
                <label for="name" class="form-label">Organization Name</label>
                <input type="text" class="form-control" id="name" name="name" value="{{ org.get('name') or '' }}" required>
            </div>

            <!-- Organization Description -->
            <!-- RK868 11/24/23 -->
            <div class="mb-3">
                <label for="description" class="form-label">Organization Description</label>
                <textarea class="form-control" id="description" name="description">{{ org.get('description') or '' }}</textarea>
            </div>

            <!-- Organization Address -->
            <!-- RK868 11/24/23 -->
            <div class="mb-3">
                <label for="address" class="form-label">Organization Address</label>
                <input type="text" class="form-control" id="address" name="address" value="{{ org.get('address') or '' }}" required>
            </div>

            <!-- City -->
            <!-- RK868 11/24/23 -->
            <div class="mb-3">
                <label for="city" class="form-label">City</label>
                <input type="text" class="form-control" id="city" name="city" value="{{ org.get('city') or '' }}" required>
            </div>
            <!-- Country/State -->
            {{ country_state_selector(country=org.get('country') or '', state=org.get('state') or '') }}

            <!-- Zip Code -->
            <div class="mb-3">
                <label for="zip" class="form-label">Zip Code</label>
                <input type="text" class="form-control" id="zip" name="zip" value="{{ org.get('zip') or '' }}" required>
            </div>

            <!-- Organization Website -->
            <div class="mb-3">
                <label for="website" class="form-label">Organization Website</label>
                <input type="url" class="form-control" id="website" name="website" value="{{ org.get('website') or '' }}">
            </div>

            <input type="submit" class="btn btn-primary" value="Save Organization" />
        </form>
    </div>
</div>
{% endblock %}

MP3/templates/nav.html
<nav class="navbar navbar-expand-lg bg-light">
    <div class="container-fluid">
        {# TODO replace my ucid mt85 with your ucid in the below a tag #}
        <a class="navbar-brand" href="{{url_for('home.index')}}">TD-rk868</a>
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse"
            data-bs-target="#navbarSupportedContent"
            aria-controls="navbarSupportedContent" aria-expanded="false"
            aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        {# TODO fill in the relevant hrefs using url_for() #}
        <!-- delete replace hrefs with #todo -->
        <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <ul class="navbar-nav me-auto mb-2 mb-lg-0">
                <!-- organization dropdown nav -->
                <li class="nav-item dropdown">
                    <a class="nav-link dropdown-toggle" href="#" role="button"
                        data-bs-toggle="dropdown" aria-expanded="false">
                        Organization
                    </a>
                    <ul class="dropdown-menu">
                        <li><a class="dropdown-item" href="{{url_for('organization.search')}}">Search</a></li>
                        <li><a class="dropdown-item" href="{{url_for('organization.add')}}">Add</a></li>
                    </ul>
                </li>
                <!-- donation dropdown nav -->
                <li class="nav-item dropdown">
                    <a class="nav-link dropdown-toggle" href="#" role="button"
                        data-bs-toggle="dropdown" aria-expanded="false">
                        Donation
                    </a>
                    <ul class="dropdown-menu">
                        <li><a class="dropdown-item" href="{{url_for('donations.search')}}">Search</a></li>
                        <li><a class="dropdown-item" href="{{url_for('donations.add')}}">Add</a></li>
                    </ul>
                </li>
                <!-- admin dropdown nav -->
                <li class="nav-item dropdown">
                    <a class="nav-link dropdown-toggle" href="#" role="button"
                        data-bs-toggle="dropdown" aria-expanded="false">
                        Admin
                    </a>
                    <ul class="dropdown-menu">
                        <li><a class="dropdown-item" href="{{url_for('admin.importCSV')}}">Import</a></li>
                    </ul>
                </li>
            </ul>
        </div>
    </div>
</nav>